apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-quote-app
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: quote
  template: 
    metadata: 
      labels:
        app: quote
    spec:
      containers: 
      - name: quote-container
        image: dhavalp16/flask-quote-app:latest
        imagePullPolicy: IfNotPresent
        ports: 
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata: 
  name: quote-service
spec:
  selector:
    app: quote
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort